# Generated by Django 5.1.2 on 2024-12-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weedGuardApp', '0005_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer')], default='admin', max_length=10),
        ),
    ]
